#! /usr/bin/python

feature_star = 0 
feature_end = 3 # not inclusive

flag_plot_gene = 2
xlennum=42
ylennum=42

xrange = range(2,xlennum+1,4)
yrange = range(2,ylennum+1,4)
rect_ixx = np.zeros(len(xrange))
rect_iyy = np.zeros(len(yrange))


#image3D = []

clfscorelist = np.zeros(1)
cvscorelist = np.zeros(1)

#tholdmatrix = [0.02]
#tholdmatrix = [0.02,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.98]
#tholdmatrix = [0.02,0.05,0.1,0.2,0.3,0.4]
#tholdmatrix = [0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.045,0.05]
# tholdmatrix = [0.015]
thold = 0.015
Maxvalue = 0.16565054

cvscoremeanlist = np.zeros(1)

#model_name = 
numberFeature  = 2
number_neighbors  = 1


totalIndex = 0 

rootoutdir = '/home/j2/Desktop/PythonTry/MLshm/oput/'

model_name = 'KNN'

flag_hyper_parameter = 1

if flag_hyper_parameter == 1:
	hyper_parameter = numberFeature
	folder_name = model_name
	folder_name_hyper_parameter = '/' + model_name + '%d' % hyper_parameter
	directory =  rootoutdir + folder_name + folder_name_hyper_parameter


#directory = '/home/j2/Desktop/PythonTry/MLshm/oput/poly/poly%d/Matrix3Dthold%04d' % (numberFeature,thold*100)




try:
    os.makedirs(directory)
except OSError as e:
    if e.errno != errno.EEXIST:
        raise



